apiVersion: syndesis.io/v1alpha1
kind: Syndesis
metadata:
  name: app
spec:
  addons:
    todo:
      enabled: true
  components:
    scheduled: false
    server:
      features:
        integrationStateCheckInterval: 60
        integrationLimit: 1
  devSupport: false
